steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    dir: 'backend'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=weaware-env > .env
  - name: 'python:3.9'
    entrypoint: 'bash'
    dir: 'backend'
    args:
      - '-c'
      - |
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy project-9ba21d45-1dfd-4108-b69:us-central1:weaware-pg --port=5433 &
        sleep 5
        pip install -r requirements.txt
        python -m spacy download xx_ent_wiki_sm
        
        # 1. Collect
        python -m ingestion.run_stage1
        
        # 2. Cluster
        python recluster.py
        
        # 3. Check for false merges
        python fix_clusters.py
        
        # 4. Update DB
        python sync_to_postgres.py --full
    env:
      - 'GOOGLE_CLOUD_PROJECT=project-9ba21d45-1dfd-4108-b69'
      - 'PYTHONUNBUFFERED=1'

options:
  logging: CLOUD_LOGGING_ONLY
